version: '3'

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
      - internal

  keycloak:
      image: quay.io/keycloak/keycloak:21.0.1
      volumes:
        - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
      command:
        - start-dev
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: true
      ports:
        - 8080:8080
      depends_on:
        - postgres
      networks:
        - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
